site_name: Módulo 2 - Mapas y OpenData
site_url: https://gis-master-m2.github.io/m2-geoweb/
site_description: Mapas y OpenData, Localización, Visualización y Análisis de GeoDatos.
site_author: geoweb
theme:
  name: 'material'
  language: 'es'
  highlightjs: true
  suppress_nextprev: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gis-master-m2/m2-geoweb"

nav:
- Inicio: index.md
- 1. Introducción a las tecnologías GeoWeb: 1_introduccion_a_las_tecnologias_geoweb.md
- 2. Introducción a Leaflet: 2_introduccion_a_la_leaflet.md
- 3. Recursos OpenData: 3_recursos_open_data.md
- 4. Plugins Leaflet: 4_plugins_leaflet.md
- 5. Taller GitHub: 5_taller_github.md
- 6. Introducción a Vector Tiles y MapBox (I): 6_introduccion_a_vector_tiles_y_mapbox_I.md
- 6. Introducción a Vector Tiles y MapBox (II): 6_introduccion_a_vector_tiles_y_mapbox_II.md
- 7. Visualización con Kepler GL: 7_visualizacion_con_kepler_gl.md
- 8. Introducción a Cesium: 8_introduccion_a_cesium.md


plugins:
    - search
    - pdf-export
