site_name: Módulo 2 - Mapas y OpenData
site_url: https://gis-master-m2.github.io/m2-geoweb/
site_description: Mapas y OpenData, Localización, Visualización y Análisis de GeoDatos.
site_author: geoweb
theme:
  name: 'bootstrap4'
  language: 'es'
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gis-master-m2/m2-geoweb"

nav:
- Inicio: index.md
- 1. Introducción a las tecnologías GeoWeb: 1_introduccion_a_las_tecnologias_geoweb.md
- 2. Introducción a Leaflet: 2_introduccion_a_la_leaflet.md
- 3. Recursos OpenData: 3_recursos_open_data.md
- 4. Plugins Leaflet: 4_Plugins_leaflet.md


plugins:
    - search
